session_name: cv (react)
start_directory: ./ # load session relative to config location (project root).
windows:
- window_name: cv (react)
  layout: main-horizontal
  options:
    main-pane-height: 35
  start_directory: ./
  shell_command_before:
    - '[ -d node_modules ] && yarn && reset'
  panes:
  - focus: true
  - pane
  - pane
  - npm start
