version: 2
updates:
- package-ecosystem: npm
  directory: "/angular"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/vue"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/react"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
