session_name: cv
start_directory: ./ # load session relative to config location (project root).
before_script: yarn
windows:
- window_name: main
  layout: main-horizontal
  focus: true
  options:
    main-pane-height: 35
  start_directory: ./
  panes:
  - focus: true
  - pane
  - pane
  - pane
- window_name: react
  layout: main-horizontal
  options:
    main-pane-height: 35
  start_directory: ./packages/react
  panes:
  - focus: true
  - pane
  - pane
  - pane
- window_name: lib
  layout: main-horizontal
  options:
    main-pane-height: 35
  start_directory: ./packages/lib
  panes:
  - focus: true
  - pane
  - pane
  - pane
