session_name: cv
start_directory: ./ # load session relative to config location (project root).
before_script: make install
windows:
- window_name: main
  layout: main-horizontal
  focus: true
  options:
    main-pane-height: 35
  start_directory: ./
  panes:
  - focus: true
  - pane
  - pane
  - pane
- window_name: cv (react)
  layout: main-horizontal
  options:
    main-pane-height: 35
  start_directory: ./react
  panes:
  - focus: true
  - pane
  - pane
  - npm start
- window_name: cv (vue.js)
  layout: main-horizontal
  options:
    main-pane-height: 35
  start_directory: ./vue
  panes:
  - focus: true
  - pane
  - pane
  - npm start
- window_name: cv (angular)
  layout: main-horizontal
  options:
    main-pane-height: 35
  start_directory: ./angular
  panes:
  - focus: true
  - pane
  - pane
  - ng serve
