import Vue from 'vue';
import Octicon from 'vue-octicon/components/Octicon';
import 'vue-octicon/icons/diff';
import 'vue-octicon/icons/mark-github';
import 'vue-octicon/icons/git-merge';
import 'vue-octicon/icons/check';
import 'vue-octicon/icons/clock';
import 'vue-octicon/icons/repo';
import 'vue-octicon/icons/book';
import 'vue-octicon/icons/code';
import 'vue-octicon/icons/home';
import 'vue-octicon/icons/dashboard';
import 'vue-octicon/icons/list-unordered';
import 'vue-octicon/icons/graph';
import 'vue-octicon/icons/search';
import 'vue-octicon/icons/checklist';
import 'vue-octicon/icons/comment-discussion';
import 'vue-octicon/icons/git-pull-request';

Vue.component('octicon', Octicon);
