name: tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: project - install
      run: yarn
    - name: lib - pull gh repos
      run: |
        env GITHUB_API_TOKEN=${{ secrets.CI_GITHUB_API_TOKEN }} yarn workspace @tony/cv-scripts run github
    - name: lib - lint, test
      run: |
        yarn workspace @tony/cv-lib run lint
        yarn workspace @tony/cv-lib run test
    - name: angular - install cli, lint, and test
      run: |
        npm install -g @angular/cli
        yarn workspace @tony/cv-angular run lint
    - name: react - lint, and test
      run: |
        yarn workspace @tony/cv-react run lint
    - name: vue - lint, and test
      run: |
        yarn workspace @tony/cv-vue run lint
